const FETCH_MENU_ITEM_REQUEST = 'FETCH_MENU_ITEM_REQUEST';
const FETCH_MENU_ITEM_SUCCESS = 'FETCH_MENU_ITEM_SUCCESS';
const FETCH_MENU_ITEM_ERROR = 'FETCH_MENU_ITEM_ERROR';

export default {
  FETCH_MENU_ITEM_REQUEST,
  FETCH_MENU_ITEM_SUCCESS,
  FETCH_MENU_ITEM_ERROR,
};
