const FETCH_MENU_LIST_REQUEST = 'FETCH_MENU_LIST_REQUEST';
const FETCH_MENU_LIST_SUCCESS = 'FETCH_MENU_LIST_SUCCESS';
const FETCH_MENU_LIST_ERROR = 'FETCH_MENU_LIST_ERROR';

export default {
  FETCH_MENU_LIST_REQUEST,
  FETCH_MENU_LIST_SUCCESS,
  FETCH_MENU_LIST_ERROR,
};
